//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export class AccountClientServiceProxy {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * 登录
     * @param body (optional) 
     * @return Success
     */
    login(body?: AccountLoginDto | undefined, cancelToken?: CancelToken): Promise<AuthenticateResultModelApiResponse> {
        let url_ = this.baseUrl + "/api/AccountClient/Login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: AxiosResponse): Promise<AuthenticateResultModelApiResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = AuthenticateResultModelApiResponse.fromJS(resultData200);
            return Promise.resolve<AuthenticateResultModelApiResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<AuthenticateResultModelApiResponse>(null as any);
    }

    /**
     * 刷新token
     * @param refreshToken (optional) 
     * @return Success
     */
    refreshToken(refreshToken?: string | undefined, cancelToken?: CancelToken): Promise<AuthenticateResultModelApiResponse> {
        let url_ = this.baseUrl + "/api/AccountClient/RefreshToken?";
        if (refreshToken === null)
            throw new globalThis.Error("The parameter 'refreshToken' cannot be null.");
        else if (refreshToken !== undefined)
            url_ += "refreshToken=" + encodeURIComponent("" + refreshToken) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRefreshToken(_response);
        });
    }

    protected processRefreshToken(response: AxiosResponse): Promise<AuthenticateResultModelApiResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = AuthenticateResultModelApiResponse.fromJS(resultData200);
            return Promise.resolve<AuthenticateResultModelApiResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<AuthenticateResultModelApiResponse>(null as any);
    }
}

export class CommonServiceProxy {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * 获取指定类型的列信息
     * @param type (optional) 
     * @return Success
     */
    getColumns(type?: string | undefined, cancelToken?: CancelToken): Promise<ListApiResponse> {
        let url_ = this.baseUrl + "/api/Common/GetColumns?";
        if (type === null)
            throw new globalThis.Error("The parameter 'type' cannot be null.");
        else if (type !== undefined)
            url_ += "type=" + encodeURIComponent("" + type) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetColumns(_response);
        });
    }

    protected processGetColumns(response: AxiosResponse): Promise<ListApiResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = ListApiResponse.fromJS(resultData200);
            return Promise.resolve<ListApiResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ListApiResponse>(null as any);
    }
}

export class FileServiceProxy {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * 文件控制器
     * @return Success
     */
    getFile( cancelToken?: CancelToken): Promise<StringApiResponse> {
        let url_ = this.baseUrl + "/api/File/GetFile";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetFile(_response);
        });
    }

    protected processGetFile(response: AxiosResponse): Promise<StringApiResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = StringApiResponse.fromJS(resultData200);
            return Promise.resolve<StringApiResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<StringApiResponse>(null as any);
    }
}

export class OrgUnitNodeServiceProxy {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * 创建或更新组织机构节点信息
     * @param body (optional) 
     * @return Success - No return data
     */
    createOrUpdate(body?: CreateOrUpdateOrgUnitNodeInput | undefined, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/OrgUnitNode/CreateOrUpdate";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCreateOrUpdate(_response);
        });
    }

    protected processCreateOrUpdate(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * 删除组织机构节点信息
     * @param body (optional) 
     * @return Success - No return data
     */
    delete(body?: EntityDto | undefined, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/OrgUnitNode/Delete";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "DELETE",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * 获取组织机构节点编辑信息
     * @param body (optional) 
     * @return Success
     */
    getForEdit(body?: EntityDto | undefined, cancelToken?: CancelToken): Promise<OrgUnitNodeForEditOutputApiResponse> {
        let url_ = this.baseUrl + "/api/OrgUnitNode/GetForEdit";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetForEdit(_response);
        });
    }

    protected processGetForEdit(response: AxiosResponse): Promise<OrgUnitNodeForEditOutputApiResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = OrgUnitNodeForEditOutputApiResponse.fromJS(resultData200);
            return Promise.resolve<OrgUnitNodeForEditOutputApiResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<OrgUnitNodeForEditOutputApiResponse>(null as any);
    }

    /**
     * 获取树数据
     * @param orgUnitNodeId (optional) 
     * @param parentOrgUnitNodeId (optional) 
     * @param filterText (optional) 
     * @param sorting (optional) 
     * @param maxResultCount (optional) 
     * @param skipCount (optional) 
     * @return Success
     */
    getTree(orgUnitNodeId?: string | undefined, parentOrgUnitNodeId?: string | undefined, filterText?: string | undefined, sorting?: string | undefined, maxResultCount?: number | undefined, skipCount?: number | undefined, cancelToken?: CancelToken): Promise<ListApiResponse2> {
        let url_ = this.baseUrl + "/api/OrgUnitNode/GetTree?";
        if (orgUnitNodeId === null)
            throw new globalThis.Error("The parameter 'orgUnitNodeId' cannot be null.");
        else if (orgUnitNodeId !== undefined)
            url_ += "OrgUnitNodeId=" + encodeURIComponent("" + orgUnitNodeId) + "&";
        if (parentOrgUnitNodeId === null)
            throw new globalThis.Error("The parameter 'parentOrgUnitNodeId' cannot be null.");
        else if (parentOrgUnitNodeId !== undefined)
            url_ += "ParentOrgUnitNodeId=" + encodeURIComponent("" + parentOrgUnitNodeId) + "&";
        if (filterText === null)
            throw new globalThis.Error("The parameter 'filterText' cannot be null.");
        else if (filterText !== undefined)
            url_ += "FilterText=" + encodeURIComponent("" + filterText) + "&";
        if (sorting === null)
            throw new globalThis.Error("The parameter 'sorting' cannot be null.");
        else if (sorting !== undefined)
            url_ += "Sorting=" + encodeURIComponent("" + sorting) + "&";
        if (maxResultCount === null)
            throw new globalThis.Error("The parameter 'maxResultCount' cannot be null.");
        else if (maxResultCount !== undefined)
            url_ += "MaxResultCount=" + encodeURIComponent("" + maxResultCount) + "&";
        if (skipCount === null)
            throw new globalThis.Error("The parameter 'skipCount' cannot be null.");
        else if (skipCount !== undefined)
            url_ += "SkipCount=" + encodeURIComponent("" + skipCount) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetTree(_response);
        });
    }

    protected processGetTree(response: AxiosResponse): Promise<ListApiResponse2> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = ListApiResponse2.fromJS(resultData200);
            return Promise.resolve<ListApiResponse2>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ListApiResponse2>(null as any);
    }
}

export class RoleServiceProxy {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * 获取角色列表分页数据
     * @param body (optional) 
     * @return Success
     */
    getPaged(body?: GetRolesInput | undefined, cancelToken?: CancelToken): Promise<PagedResultDtoApiResponse> {
        let url_ = this.baseUrl + "/api/Role/GetPaged";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetPaged(_response);
        });
    }

    protected processGetPaged(response: AxiosResponse): Promise<PagedResultDtoApiResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = PagedResultDtoApiResponse.fromJS(resultData200);
            return Promise.resolve<PagedResultDtoApiResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<PagedResultDtoApiResponse>(null as any);
    }

    /**
     * 创建或更新角色
     * @param body (optional) 
     * @return Success - No return data
     */
    createOrUpdate(body?: CreateOrUpdateRoleInput | undefined, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/Role/CreateOrUpdate";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCreateOrUpdate(_response);
        });
    }

    protected processCreateOrUpdate(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * 获取角色信息
     * @param body (optional) 
     * @return Success
     */
    getForEdit(body?: EntityDto | undefined, cancelToken?: CancelToken): Promise<RoleDtoApiResponse> {
        let url_ = this.baseUrl + "/api/Role/GetForEdit";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetForEdit(_response);
        });
    }

    protected processGetForEdit(response: AxiosResponse): Promise<RoleDtoApiResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = RoleDtoApiResponse.fromJS(resultData200);
            return Promise.resolve<RoleDtoApiResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<RoleDtoApiResponse>(null as any);
    }

    /**
     * 获取下拉列表
     * @param body (optional) 
     * @return Success
     */
    getDropDownList(body?: GetDropDownListInput | undefined, cancelToken?: CancelToken): Promise<ListApiResponse3> {
        let url_ = this.baseUrl + "/api/Role/GetDropDownList";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetDropDownList(_response);
        });
    }

    protected processGetDropDownList(response: AxiosResponse): Promise<ListApiResponse3> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = ListApiResponse3.fromJS(resultData200);
            return Promise.resolve<ListApiResponse3>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ListApiResponse3>(null as any);
    }
}

export class UserServiceProxy {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * 创建或更新用户
     * @param body (optional) 
     * @return Success - No return data
     */
    createOrUpdate(body?: CreateOrUpdateUserInput | undefined, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/User/CreateOrUpdate";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCreateOrUpdate(_response);
        });
    }

    protected processCreateOrUpdate(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * 获取用户信息
     * @param body (optional) 
     * @return Success
     */
    getForEdit(body?: EntityDto | undefined, cancelToken?: CancelToken): Promise<UserDtoApiResponse> {
        let url_ = this.baseUrl + "/api/User/GetForEdit";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetForEdit(_response);
        });
    }

    protected processGetForEdit(response: AxiosResponse): Promise<UserDtoApiResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = UserDtoApiResponse.fromJS(resultData200);
            return Promise.resolve<UserDtoApiResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<UserDtoApiResponse>(null as any);
    }

    /**
     * 获取用户列表分页数据
     * @param body (optional) 
     * @return Success
     */
    getPaged(body?: GetUsersInput | undefined, cancelToken?: CancelToken): Promise<PagedResultDtoApiResponse2> {
        let url_ = this.baseUrl + "/api/User/GetPaged";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetPaged(_response);
        });
    }

    protected processGetPaged(response: AxiosResponse): Promise<PagedResultDtoApiResponse2> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = PagedResultDtoApiResponse2.fromJS(resultData200);
            return Promise.resolve<PagedResultDtoApiResponse2>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<PagedResultDtoApiResponse2>(null as any);
    }

    /**
     * 批量分配角色
     * @param body (optional) 
     * @return Success - No return data
     */
    assignRole(body?: AssignRoleInput | undefined, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/User/AssignRole";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAssignRole(_response);
        });
    }

    protected processAssignRole(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * 获取所有权限
     * @return Success
     */
    getAllPermission( cancelToken?: CancelToken): Promise<ListApiResponse4> {
        let url_ = this.baseUrl + "/api/User/GetAllPermission";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetAllPermission(_response);
        });
    }

    protected processGetAllPermission(response: AxiosResponse): Promise<ListApiResponse4> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = ListApiResponse4.fromJS(resultData200);
            return Promise.resolve<ListApiResponse4>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ListApiResponse4>(null as any);
    }

    /**
     * @return No Content - Method does not return any data
     */
    initPermission( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/User/InitPermission";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processInitPermission(_response);
        });
    }

    protected processInitPermission(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }
}

export class AccountLoginDto implements IAccountLoginDto {
    /** 用户名 */
    userName!: string;
    /** 密码 */
    password!: string;
    /** 手机号 */
    phoneNumber!: string | undefined;
    /** 客户端，PC，App */
    clientType!: string | undefined;
    /** 记住我 */
    rememberMe!: boolean;
    /** 是否刷新Token */
    isRefresh!: boolean;
    /** 是否Api登录 */
    isApiLogin!: boolean;

    constructor(data?: IAccountLoginDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userName = _data["UserName"];
            this.password = _data["Password"];
            this.phoneNumber = _data["PhoneNumber"];
            this.clientType = _data["ClientType"];
            this.rememberMe = _data["RememberMe"];
            this.isRefresh = _data["IsRefresh"];
            this.isApiLogin = _data["IsApiLogin"];
        }
    }

    static fromJS(data: any): AccountLoginDto {
        data = typeof data === 'object' ? data : {};
        let result = new AccountLoginDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["UserName"] = this.userName;
        data["Password"] = this.password;
        data["PhoneNumber"] = this.phoneNumber;
        data["ClientType"] = this.clientType;
        data["RememberMe"] = this.rememberMe;
        data["IsRefresh"] = this.isRefresh;
        data["IsApiLogin"] = this.isApiLogin;
        return data;
    }
}

export interface IAccountLoginDto {
    /** 用户名 */
    userName: string;
    /** 密码 */
    password: string;
    /** 手机号 */
    phoneNumber: string | undefined;
    /** 客户端，PC，App */
    clientType: string | undefined;
    /** 记住我 */
    rememberMe: boolean;
    /** 是否刷新Token */
    isRefresh: boolean;
    /** 是否Api登录 */
    isApiLogin: boolean;
}

export class AuthenticateResultModel implements IAuthenticateResultModel {
    /** 用户头像 */
    avatar!: string | undefined;
    /** 用户名称 */
    userName!: string | undefined;
    /** 用户昵称 */
    nickName!: string | undefined;
    /** 用户角色 */
    roles!: string[] | undefined;
    /** 用户权限 */
    permissions!: string[] | undefined;
    /** 过期时间 */
    expires!: Date;
    /** 加密后的密码 */
    password!: string | undefined;
    accessToken!: string | undefined;
    encryptedAccessToken!: string | undefined;
    refreshToken!: string | undefined;
    expireInSeconds!: number;
    userId!: string | undefined;
    shouldResetPassword!: boolean;
    passwordResetCode!: string | undefined;
    refreshTokenExpire!: Date;
    returnUrl!: string | undefined;
    waitingForActivation!: boolean;

    constructor(data?: IAuthenticateResultModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.avatar = _data["Avatar"];
            this.userName = _data["UserName"];
            this.nickName = _data["NickName"];
            if (Array.isArray(_data["Roles"])) {
                this.roles = [] as any;
                for (let item of _data["Roles"])
                    this.roles!.push(item);
            }
            if (Array.isArray(_data["Permissions"])) {
                this.permissions = [] as any;
                for (let item of _data["Permissions"])
                    this.permissions!.push(item);
            }
            this.expires = _data["Expires"] ? new Date(_data["Expires"].toString()) : undefined as any;
            this.password = _data["Password"];
            this.accessToken = _data["AccessToken"];
            this.encryptedAccessToken = _data["EncryptedAccessToken"];
            this.refreshToken = _data["RefreshToken"];
            this.expireInSeconds = _data["ExpireInSeconds"];
            this.userId = _data["UserId"];
            this.shouldResetPassword = _data["ShouldResetPassword"];
            this.passwordResetCode = _data["PasswordResetCode"];
            this.refreshTokenExpire = _data["RefreshTokenExpire"] ? new Date(_data["RefreshTokenExpire"].toString()) : undefined as any;
            this.returnUrl = _data["ReturnUrl"];
            this.waitingForActivation = _data["WaitingForActivation"];
        }
    }

    static fromJS(data: any): AuthenticateResultModel {
        data = typeof data === 'object' ? data : {};
        let result = new AuthenticateResultModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Avatar"] = this.avatar;
        data["UserName"] = this.userName;
        data["NickName"] = this.nickName;
        if (Array.isArray(this.roles)) {
            data["Roles"] = [];
            for (let item of this.roles)
                data["Roles"].push(item);
        }
        if (Array.isArray(this.permissions)) {
            data["Permissions"] = [];
            for (let item of this.permissions)
                data["Permissions"].push(item);
        }
        data["Expires"] = this.expires ? this.expires.toISOString() : undefined as any;
        data["Password"] = this.password;
        data["AccessToken"] = this.accessToken;
        data["EncryptedAccessToken"] = this.encryptedAccessToken;
        data["RefreshToken"] = this.refreshToken;
        data["ExpireInSeconds"] = this.expireInSeconds;
        data["UserId"] = this.userId;
        data["ShouldResetPassword"] = this.shouldResetPassword;
        data["PasswordResetCode"] = this.passwordResetCode;
        data["RefreshTokenExpire"] = this.refreshTokenExpire ? this.refreshTokenExpire.toISOString() : undefined as any;
        data["ReturnUrl"] = this.returnUrl;
        data["WaitingForActivation"] = this.waitingForActivation;
        return data;
    }
}

export interface IAuthenticateResultModel {
    /** 用户头像 */
    avatar: string | undefined;
    /** 用户名称 */
    userName: string | undefined;
    /** 用户昵称 */
    nickName: string | undefined;
    /** 用户角色 */
    roles: string[] | undefined;
    /** 用户权限 */
    permissions: string[] | undefined;
    /** 过期时间 */
    expires: Date;
    /** 加密后的密码 */
    password: string | undefined;
    accessToken: string | undefined;
    encryptedAccessToken: string | undefined;
    refreshToken: string | undefined;
    expireInSeconds: number;
    userId: string | undefined;
    shouldResetPassword: boolean;
    passwordResetCode: string | undefined;
    refreshTokenExpire: Date;
    returnUrl: string | undefined;
    waitingForActivation: boolean;
}

export class AuthenticateResultModelApiResponse implements IAuthenticateResultModelApiResponse {
    data!: AuthenticateResultModel | undefined;
    code!: number;
    success!: boolean;
    message!: string | undefined;

    constructor(data?: IAuthenticateResultModelApiResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.data = _data["Data"] ? AuthenticateResultModel.fromJS(_data["Data"]) : undefined as any;
            this.code = _data["Code"];
            this.success = _data["Success"];
            this.message = _data["Message"];
        }
    }

    static fromJS(data: any): AuthenticateResultModelApiResponse {
        data = typeof data === 'object' ? data : {};
        let result = new AuthenticateResultModelApiResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Data"] = this.data ? this.data.toJSON() : undefined as any;
        data["Code"] = this.code;
        data["Success"] = this.success;
        data["Message"] = this.message;
        return data;
    }
}

export interface IAuthenticateResultModelApiResponse {
    data: AuthenticateResultModel | undefined;
    code: number;
    success: boolean;
    message: string | undefined;
}

export class ColumnDto implements IColumnDto {
    /** 显示的标题 */
    label!: string | undefined;
    /** 字段名称 */
    prop!: string | undefined;
    /** 指定插槽 */
    slot!: string | undefined;
    /** 数据在排序时所使用排序策略的轮转顺序，仅当 `sortable` 为 `true` 时有效。
需传入一个数组，随着用户点击表头，该列依次按照数组中元素的顺序进行排序，
默认值为 `['ascending', 'descending', null]` */
    sortOrders!: string[] | undefined;
    /** 操作列按钮 */
    operations!: string[] | undefined;

    constructor(data?: IColumnDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.label = _data["label"];
            this.prop = _data["prop"];
            this.slot = _data["slot"];
            if (Array.isArray(_data["sortOrders"])) {
                this.sortOrders = [] as any;
                for (let item of _data["sortOrders"])
                    this.sortOrders!.push(item);
            }
            if (Array.isArray(_data["operations"])) {
                this.operations = [] as any;
                for (let item of _data["operations"])
                    this.operations!.push(item);
            }
        }
    }

    static fromJS(data: any): ColumnDto {
        data = typeof data === 'object' ? data : {};
        let result = new ColumnDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["label"] = this.label;
        data["prop"] = this.prop;
        data["slot"] = this.slot;
        if (Array.isArray(this.sortOrders)) {
            data["sortOrders"] = [];
            for (let item of this.sortOrders)
                data["sortOrders"].push(item);
        }
        if (Array.isArray(this.operations)) {
            data["operations"] = [];
            for (let item of this.operations)
                data["operations"].push(item);
        }
        return data;
    }
}

export interface IColumnDto {
    /** 显示的标题 */
    label: string | undefined;
    /** 字段名称 */
    prop: string | undefined;
    /** 指定插槽 */
    slot: string | undefined;
    /** 数据在排序时所使用排序策略的轮转顺序，仅当 `sortable` 为 `true` 时有效。
需传入一个数组，随着用户点击表头，该列依次按照数组中元素的顺序进行排序，
默认值为 `['ascending', 'descending', null]` */
    sortOrders: string[] | undefined;
    /** 操作列按钮 */
    operations: string[] | undefined;
}

export class ListApiResponse implements IListApiResponse {
    data!: ColumnDto[] | undefined;
    code!: number;
    success!: boolean;
    message!: string | undefined;

    constructor(data?: IListApiResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["Data"])) {
                this.data = [] as any;
                for (let item of _data["Data"])
                    this.data!.push(ColumnDto.fromJS(item));
            }
            this.code = _data["Code"];
            this.success = _data["Success"];
            this.message = _data["Message"];
        }
    }

    static fromJS(data: any): ListApiResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ListApiResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.data)) {
            data["Data"] = [];
            for (let item of this.data)
                data["Data"].push(item ? item.toJSON() : undefined as any);
        }
        data["Code"] = this.code;
        data["Success"] = this.success;
        data["Message"] = this.message;
        return data;
    }
}

export interface IListApiResponse {
    data: ColumnDto[] | undefined;
    code: number;
    success: boolean;
    message: string | undefined;
}

export class StringApiResponse implements IStringApiResponse {
    data!: string | undefined;
    code!: number;
    success!: boolean;
    message!: string | undefined;

    constructor(data?: IStringApiResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.data = _data["Data"];
            this.code = _data["Code"];
            this.success = _data["Success"];
            this.message = _data["Message"];
        }
    }

    static fromJS(data: any): StringApiResponse {
        data = typeof data === 'object' ? data : {};
        let result = new StringApiResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Data"] = this.data;
        data["Code"] = this.code;
        data["Success"] = this.success;
        data["Message"] = this.message;
        return data;
    }
}

export interface IStringApiResponse {
    data: string | undefined;
    code: number;
    success: boolean;
    message: string | undefined;
}

export enum OrgUnitNodeStatus {
    _0 = 0,
    _1 = 1,
}

export class OrgUnitNodeEditDto implements IOrgUnitNodeEditDto {
    /** id */
    id!: string | undefined;
    /** 名称 */
    name!: string | undefined;
    /** 父级Id */
    parentId!: string | undefined;
    /** 状态 */
    status!: OrgUnitNodeStatus;

    constructor(data?: IOrgUnitNodeEditDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.name = _data["Name"];
            this.parentId = _data["ParentId"];
            this.status = _data["Status"];
        }
    }

    static fromJS(data: any): OrgUnitNodeEditDto {
        data = typeof data === 'object' ? data : {};
        let result = new OrgUnitNodeEditDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Name"] = this.name;
        data["ParentId"] = this.parentId;
        data["Status"] = this.status;
        return data;
    }
}

export interface IOrgUnitNodeEditDto {
    /** id */
    id: string | undefined;
    /** 名称 */
    name: string | undefined;
    /** 父级Id */
    parentId: string | undefined;
    /** 状态 */
    status: OrgUnitNodeStatus;
}

export class CreateOrUpdateOrgUnitNodeInput implements ICreateOrUpdateOrgUnitNodeInput {
    orgUnitNode!: OrgUnitNodeEditDto;

    constructor(data?: ICreateOrUpdateOrgUnitNodeInput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.orgUnitNode = new OrgUnitNodeEditDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.orgUnitNode = _data["OrgUnitNode"] ? OrgUnitNodeEditDto.fromJS(_data["OrgUnitNode"]) : new OrgUnitNodeEditDto();
        }
    }

    static fromJS(data: any): CreateOrUpdateOrgUnitNodeInput {
        data = typeof data === 'object' ? data : {};
        let result = new CreateOrUpdateOrgUnitNodeInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["OrgUnitNode"] = this.orgUnitNode ? this.orgUnitNode.toJSON() : undefined as any;
        return data;
    }
}

export interface ICreateOrUpdateOrgUnitNodeInput {
    orgUnitNode: OrgUnitNodeEditDto;
}

export class EntityDto implements IEntityDto {
    id!: string | undefined;

    constructor(data?: IEntityDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
        }
    }

    static fromJS(data: any): EntityDto {
        data = typeof data === 'object' ? data : {};
        let result = new EntityDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        return data;
    }
}

export interface IEntityDto {
    id: string | undefined;
}

export class OrgUnitNodeForEditOutput implements IOrgUnitNodeForEditOutput {
    orgUnitNode!: OrgUnitNodeEditDto;

    constructor(data?: IOrgUnitNodeForEditOutput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.orgUnitNode = new OrgUnitNodeEditDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.orgUnitNode = _data["OrgUnitNode"] ? OrgUnitNodeEditDto.fromJS(_data["OrgUnitNode"]) : new OrgUnitNodeEditDto();
        }
    }

    static fromJS(data: any): OrgUnitNodeForEditOutput {
        data = typeof data === 'object' ? data : {};
        let result = new OrgUnitNodeForEditOutput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["OrgUnitNode"] = this.orgUnitNode ? this.orgUnitNode.toJSON() : undefined as any;
        return data;
    }
}

export interface IOrgUnitNodeForEditOutput {
    orgUnitNode: OrgUnitNodeEditDto;
}

export class OrgUnitNodeForEditOutputApiResponse implements IOrgUnitNodeForEditOutputApiResponse {
    data!: OrgUnitNodeForEditOutput | undefined;
    code!: number;
    success!: boolean;
    message!: string | undefined;

    constructor(data?: IOrgUnitNodeForEditOutputApiResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.data = _data["Data"] ? OrgUnitNodeForEditOutput.fromJS(_data["Data"]) : undefined as any;
            this.code = _data["Code"];
            this.success = _data["Success"];
            this.message = _data["Message"];
        }
    }

    static fromJS(data: any): OrgUnitNodeForEditOutputApiResponse {
        data = typeof data === 'object' ? data : {};
        let result = new OrgUnitNodeForEditOutputApiResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Data"] = this.data ? this.data.toJSON() : undefined as any;
        data["Code"] = this.code;
        data["Success"] = this.success;
        data["Message"] = this.message;
        return data;
    }
}

export interface IOrgUnitNodeForEditOutputApiResponse {
    data: OrgUnitNodeForEditOutput | undefined;
    code: number;
    success: boolean;
    message: string | undefined;
}

export class OrgUnitNodeListDto implements IOrgUnitNodeListDto {
    id!: string | undefined;
    totalChild!: number;

    constructor(data?: IOrgUnitNodeListDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.totalChild = _data["TotalChild"];
        }
    }

    static fromJS(data: any): OrgUnitNodeListDto {
        data = typeof data === 'object' ? data : {};
        let result = new OrgUnitNodeListDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["TotalChild"] = this.totalChild;
        return data;
    }
}

export interface IOrgUnitNodeListDto {
    id: string | undefined;
    totalChild: number;
}

export class ListApiResponse2 implements IListApiResponse2 {
    data!: OrgUnitNodeListDto[] | undefined;
    code!: number;
    success!: boolean;
    message!: string | undefined;

    constructor(data?: IListApiResponse2) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["Data"])) {
                this.data = [] as any;
                for (let item of _data["Data"])
                    this.data!.push(OrgUnitNodeListDto.fromJS(item));
            }
            this.code = _data["Code"];
            this.success = _data["Success"];
            this.message = _data["Message"];
        }
    }

    static fromJS(data: any): ListApiResponse2 {
        data = typeof data === 'object' ? data : {};
        let result = new ListApiResponse2();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.data)) {
            data["Data"] = [];
            for (let item of this.data)
                data["Data"].push(item ? item.toJSON() : undefined as any);
        }
        data["Code"] = this.code;
        data["Success"] = this.success;
        data["Message"] = this.message;
        return data;
    }
}

export interface IListApiResponse2 {
    data: OrgUnitNodeListDto[] | undefined;
    code: number;
    success: boolean;
    message: string | undefined;
}

export class RoleListDto implements IRoleListDto {
    id!: string | undefined;
    name!: string | undefined;
    displayName!: string | undefined;
    isStatic!: boolean;
    isDefault!: boolean;
    creationTime!: Date;
    opertion!: string | undefined;

    constructor(data?: IRoleListDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.name = _data["Name"];
            this.displayName = _data["DisplayName"];
            this.isStatic = _data["IsStatic"];
            this.isDefault = _data["IsDefault"];
            this.creationTime = _data["CreationTime"] ? new Date(_data["CreationTime"].toString()) : undefined as any;
            this.opertion = _data["Opertion"];
        }
    }

    static fromJS(data: any): RoleListDto {
        data = typeof data === 'object' ? data : {};
        let result = new RoleListDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Name"] = this.name;
        data["DisplayName"] = this.displayName;
        data["IsStatic"] = this.isStatic;
        data["IsDefault"] = this.isDefault;
        data["CreationTime"] = this.creationTime ? this.creationTime.toISOString() : undefined as any;
        data["Opertion"] = this.opertion;
        return data;
    }
}

export interface IRoleListDto {
    id: string | undefined;
    name: string | undefined;
    displayName: string | undefined;
    isStatic: boolean;
    isDefault: boolean;
    creationTime: Date;
    opertion: string | undefined;
}

export class PagedResultDto implements IPagedResultDto {
    totalCount!: number;
    items!: RoleListDto[] | undefined;

    constructor(data?: IPagedResultDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.totalCount = _data["TotalCount"];
            if (Array.isArray(_data["Items"])) {
                this.items = [] as any;
                for (let item of _data["Items"])
                    this.items!.push(RoleListDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): PagedResultDto {
        data = typeof data === 'object' ? data : {};
        let result = new PagedResultDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["TotalCount"] = this.totalCount;
        if (Array.isArray(this.items)) {
            data["Items"] = [];
            for (let item of this.items)
                data["Items"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IPagedResultDto {
    totalCount: number;
    items: RoleListDto[] | undefined;
}

export class PagedResultDtoApiResponse implements IPagedResultDtoApiResponse {
    data!: PagedResultDto | undefined;
    code!: number;
    success!: boolean;
    message!: string | undefined;

    constructor(data?: IPagedResultDtoApiResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.data = _data["Data"] ? PagedResultDto.fromJS(_data["Data"]) : undefined as any;
            this.code = _data["Code"];
            this.success = _data["Success"];
            this.message = _data["Message"];
        }
    }

    static fromJS(data: any): PagedResultDtoApiResponse {
        data = typeof data === 'object' ? data : {};
        let result = new PagedResultDtoApiResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Data"] = this.data ? this.data.toJSON() : undefined as any;
        data["Code"] = this.code;
        data["Success"] = this.success;
        data["Message"] = this.message;
        return data;
    }
}

export interface IPagedResultDtoApiResponse {
    data: PagedResultDto | undefined;
    code: number;
    success: boolean;
    message: string | undefined;
}

export class GetRolesInput implements IGetRolesInput {
    filterText!: string | undefined;
    sorting!: string | undefined;
    maxResultCount!: number;
    skipCount!: number;

    constructor(data?: IGetRolesInput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.filterText = _data["FilterText"];
            this.sorting = _data["Sorting"];
            this.maxResultCount = _data["MaxResultCount"];
            this.skipCount = _data["SkipCount"];
        }
    }

    static fromJS(data: any): GetRolesInput {
        data = typeof data === 'object' ? data : {};
        let result = new GetRolesInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["FilterText"] = this.filterText;
        data["Sorting"] = this.sorting;
        data["MaxResultCount"] = this.maxResultCount;
        data["SkipCount"] = this.skipCount;
        return data;
    }
}

export interface IGetRolesInput {
    filterText: string | undefined;
    sorting: string | undefined;
    maxResultCount: number;
    skipCount: number;
}

export class RoleDto implements IRoleDto {
    /** 主键 */
    id!: string | undefined;
    /** 显示名称 */
    displayName!: string | undefined;
    /** 角色名称 */
    name!: string | undefined;
    /** 是否静态角色，静态角色无法删除，无法更改其名称。它们可以通过编程方式使用。 */
    isStatic!: boolean;
    /** 该角色是否将被分配给新用户？ */
    isDefault!: boolean;

    constructor(data?: IRoleDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.displayName = _data["DisplayName"];
            this.name = _data["Name"];
            this.isStatic = _data["IsStatic"];
            this.isDefault = _data["IsDefault"];
        }
    }

    static fromJS(data: any): RoleDto {
        data = typeof data === 'object' ? data : {};
        let result = new RoleDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["DisplayName"] = this.displayName;
        data["Name"] = this.name;
        data["IsStatic"] = this.isStatic;
        data["IsDefault"] = this.isDefault;
        return data;
    }
}

export interface IRoleDto {
    /** 主键 */
    id: string | undefined;
    /** 显示名称 */
    displayName: string | undefined;
    /** 角色名称 */
    name: string | undefined;
    /** 是否静态角色，静态角色无法删除，无法更改其名称。它们可以通过编程方式使用。 */
    isStatic: boolean;
    /** 该角色是否将被分配给新用户？ */
    isDefault: boolean;
}

export class CreateOrUpdateRoleInput implements ICreateOrUpdateRoleInput {
    role!: RoleDto;

    constructor(data?: ICreateOrUpdateRoleInput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.role = new RoleDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.role = _data["Role"] ? RoleDto.fromJS(_data["Role"]) : new RoleDto();
        }
    }

    static fromJS(data: any): CreateOrUpdateRoleInput {
        data = typeof data === 'object' ? data : {};
        let result = new CreateOrUpdateRoleInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Role"] = this.role ? this.role.toJSON() : undefined as any;
        return data;
    }
}

export interface ICreateOrUpdateRoleInput {
    role: RoleDto;
}

export class RoleDtoApiResponse implements IRoleDtoApiResponse {
    data!: RoleDto | undefined;
    code!: number;
    success!: boolean;
    message!: string | undefined;

    constructor(data?: IRoleDtoApiResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.data = _data["Data"] ? RoleDto.fromJS(_data["Data"]) : undefined as any;
            this.code = _data["Code"];
            this.success = _data["Success"];
            this.message = _data["Message"];
        }
    }

    static fromJS(data: any): RoleDtoApiResponse {
        data = typeof data === 'object' ? data : {};
        let result = new RoleDtoApiResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Data"] = this.data ? this.data.toJSON() : undefined as any;
        data["Code"] = this.code;
        data["Success"] = this.success;
        data["Message"] = this.message;
        return data;
    }
}

export interface IRoleDtoApiResponse {
    data: RoleDto | undefined;
    code: number;
    success: boolean;
    message: string | undefined;
}

export class DropDownListDto implements IDropDownListDto {
    key!: string | undefined;
    value!: string | undefined;

    constructor(data?: IDropDownListDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.key = _data["Key"];
            this.value = _data["Value"];
        }
    }

    static fromJS(data: any): DropDownListDto {
        data = typeof data === 'object' ? data : {};
        let result = new DropDownListDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Key"] = this.key;
        data["Value"] = this.value;
        return data;
    }
}

export interface IDropDownListDto {
    key: string | undefined;
    value: string | undefined;
}

export class ListApiResponse3 implements IListApiResponse3 {
    data!: DropDownListDto[] | undefined;
    code!: number;
    success!: boolean;
    message!: string | undefined;

    constructor(data?: IListApiResponse3) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["Data"])) {
                this.data = [] as any;
                for (let item of _data["Data"])
                    this.data!.push(DropDownListDto.fromJS(item));
            }
            this.code = _data["Code"];
            this.success = _data["Success"];
            this.message = _data["Message"];
        }
    }

    static fromJS(data: any): ListApiResponse3 {
        data = typeof data === 'object' ? data : {};
        let result = new ListApiResponse3();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.data)) {
            data["Data"] = [];
            for (let item of this.data)
                data["Data"].push(item ? item.toJSON() : undefined as any);
        }
        data["Code"] = this.code;
        data["Success"] = this.success;
        data["Message"] = this.message;
        return data;
    }
}

export interface IListApiResponse3 {
    data: DropDownListDto[] | undefined;
    code: number;
    success: boolean;
    message: string | undefined;
}

export class GetDropDownListInput implements IGetDropDownListInput {
    /** 已选的ids值 */
    ids!: string[] | undefined;
    filterText!: string | undefined;
    sorting!: string | undefined;
    maxResultCount!: number;
    skipCount!: number;

    constructor(data?: IGetDropDownListInput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["Ids"])) {
                this.ids = [] as any;
                for (let item of _data["Ids"])
                    this.ids!.push(item);
            }
            this.filterText = _data["FilterText"];
            this.sorting = _data["Sorting"];
            this.maxResultCount = _data["MaxResultCount"];
            this.skipCount = _data["SkipCount"];
        }
    }

    static fromJS(data: any): GetDropDownListInput {
        data = typeof data === 'object' ? data : {};
        let result = new GetDropDownListInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.ids)) {
            data["Ids"] = [];
            for (let item of this.ids)
                data["Ids"].push(item);
        }
        data["FilterText"] = this.filterText;
        data["Sorting"] = this.sorting;
        data["MaxResultCount"] = this.maxResultCount;
        data["SkipCount"] = this.skipCount;
        return data;
    }
}

export interface IGetDropDownListInput {
    /** 已选的ids值 */
    ids: string[] | undefined;
    filterText: string | undefined;
    sorting: string | undefined;
    maxResultCount: number;
    skipCount: number;
}

export class UserDto implements IUserDto {
    id!: string | undefined;
    fullName!: string | undefined;
    userName!: string | undefined;
    password!: string | undefined;
    email!: string | undefined;
    phoneNumber!: string | undefined;
    isActive!: boolean;
    creationTime!: Date;

    constructor(data?: IUserDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.fullName = _data["FullName"];
            this.userName = _data["UserName"];
            this.password = _data["Password"];
            this.email = _data["Email"];
            this.phoneNumber = _data["PhoneNumber"];
            this.isActive = _data["IsActive"];
            this.creationTime = _data["CreationTime"] ? new Date(_data["CreationTime"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): UserDto {
        data = typeof data === 'object' ? data : {};
        let result = new UserDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["FullName"] = this.fullName;
        data["UserName"] = this.userName;
        data["Password"] = this.password;
        data["Email"] = this.email;
        data["PhoneNumber"] = this.phoneNumber;
        data["IsActive"] = this.isActive;
        data["CreationTime"] = this.creationTime ? this.creationTime.toISOString() : undefined as any;
        return data;
    }
}

export interface IUserDto {
    id: string | undefined;
    fullName: string | undefined;
    userName: string | undefined;
    password: string | undefined;
    email: string | undefined;
    phoneNumber: string | undefined;
    isActive: boolean;
    creationTime: Date;
}

export class CreateOrUpdateUserInput implements ICreateOrUpdateUserInput {
    user!: UserDto;

    constructor(data?: ICreateOrUpdateUserInput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.user = new UserDto();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.user = _data["User"] ? UserDto.fromJS(_data["User"]) : new UserDto();
        }
    }

    static fromJS(data: any): CreateOrUpdateUserInput {
        data = typeof data === 'object' ? data : {};
        let result = new CreateOrUpdateUserInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["User"] = this.user ? this.user.toJSON() : undefined as any;
        return data;
    }
}

export interface ICreateOrUpdateUserInput {
    user: UserDto;
}

export class UserDtoApiResponse implements IUserDtoApiResponse {
    data!: UserDto | undefined;
    code!: number;
    success!: boolean;
    message!: string | undefined;

    constructor(data?: IUserDtoApiResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.data = _data["Data"] ? UserDto.fromJS(_data["Data"]) : undefined as any;
            this.code = _data["Code"];
            this.success = _data["Success"];
            this.message = _data["Message"];
        }
    }

    static fromJS(data: any): UserDtoApiResponse {
        data = typeof data === 'object' ? data : {};
        let result = new UserDtoApiResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Data"] = this.data ? this.data.toJSON() : undefined as any;
        data["Code"] = this.code;
        data["Success"] = this.success;
        data["Message"] = this.message;
        return data;
    }
}

export interface IUserDtoApiResponse {
    data: UserDto | undefined;
    code: number;
    success: boolean;
    message: string | undefined;
}

export class UserListDto implements IUserListDto {
    /** 主键 */
    id!: string | undefined;
    fullName!: string | undefined;
    userName!: string | undefined;
    email!: string | undefined;
    phoneNumber!: string | undefined;
    orgUnitNodeName!: string | undefined;
    roleName!: string[] | undefined;
    isActive!: boolean;
    /** 是否管理员 */
    isSuperAdmin!: boolean;
    creationTime!: Date;

    constructor(data?: IUserListDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.fullName = _data["FullName"];
            this.userName = _data["UserName"];
            this.email = _data["Email"];
            this.phoneNumber = _data["PhoneNumber"];
            this.orgUnitNodeName = _data["OrgUnitNodeName"];
            if (Array.isArray(_data["RoleName"])) {
                this.roleName = [] as any;
                for (let item of _data["RoleName"])
                    this.roleName!.push(item);
            }
            this.isActive = _data["IsActive"];
            this.isSuperAdmin = _data["IsSuperAdmin"];
            this.creationTime = _data["CreationTime"] ? new Date(_data["CreationTime"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): UserListDto {
        data = typeof data === 'object' ? data : {};
        let result = new UserListDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["FullName"] = this.fullName;
        data["UserName"] = this.userName;
        data["Email"] = this.email;
        data["PhoneNumber"] = this.phoneNumber;
        data["OrgUnitNodeName"] = this.orgUnitNodeName;
        if (Array.isArray(this.roleName)) {
            data["RoleName"] = [];
            for (let item of this.roleName)
                data["RoleName"].push(item);
        }
        data["IsActive"] = this.isActive;
        data["IsSuperAdmin"] = this.isSuperAdmin;
        data["CreationTime"] = this.creationTime ? this.creationTime.toISOString() : undefined as any;
        return data;
    }
}

export interface IUserListDto {
    /** 主键 */
    id: string | undefined;
    fullName: string | undefined;
    userName: string | undefined;
    email: string | undefined;
    phoneNumber: string | undefined;
    orgUnitNodeName: string | undefined;
    roleName: string[] | undefined;
    isActive: boolean;
    /** 是否管理员 */
    isSuperAdmin: boolean;
    creationTime: Date;
}

export class PagedResultDto2 implements IPagedResultDto2 {
    totalCount!: number;
    items!: UserListDto[] | undefined;

    constructor(data?: IPagedResultDto2) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.totalCount = _data["TotalCount"];
            if (Array.isArray(_data["Items"])) {
                this.items = [] as any;
                for (let item of _data["Items"])
                    this.items!.push(UserListDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): PagedResultDto2 {
        data = typeof data === 'object' ? data : {};
        let result = new PagedResultDto2();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["TotalCount"] = this.totalCount;
        if (Array.isArray(this.items)) {
            data["Items"] = [];
            for (let item of this.items)
                data["Items"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IPagedResultDto2 {
    totalCount: number;
    items: UserListDto[] | undefined;
}

export class PagedResultDtoApiResponse2 implements IPagedResultDtoApiResponse2 {
    data!: PagedResultDto2 | undefined;
    code!: number;
    success!: boolean;
    message!: string | undefined;

    constructor(data?: IPagedResultDtoApiResponse2) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.data = _data["Data"] ? PagedResultDto2.fromJS(_data["Data"]) : undefined as any;
            this.code = _data["Code"];
            this.success = _data["Success"];
            this.message = _data["Message"];
        }
    }

    static fromJS(data: any): PagedResultDtoApiResponse2 {
        data = typeof data === 'object' ? data : {};
        let result = new PagedResultDtoApiResponse2();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Data"] = this.data ? this.data.toJSON() : undefined as any;
        data["Code"] = this.code;
        data["Success"] = this.success;
        data["Message"] = this.message;
        return data;
    }
}

export interface IPagedResultDtoApiResponse2 {
    data: PagedResultDto2 | undefined;
    code: number;
    success: boolean;
    message: string | undefined;
}

export class GetUsersInput implements IGetUsersInput {
    filterText!: string | undefined;
    sorting!: string | undefined;
    maxResultCount!: number;
    skipCount!: number;

    constructor(data?: IGetUsersInput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.filterText = _data["FilterText"];
            this.sorting = _data["Sorting"];
            this.maxResultCount = _data["MaxResultCount"];
            this.skipCount = _data["SkipCount"];
        }
    }

    static fromJS(data: any): GetUsersInput {
        data = typeof data === 'object' ? data : {};
        let result = new GetUsersInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["FilterText"] = this.filterText;
        data["Sorting"] = this.sorting;
        data["MaxResultCount"] = this.maxResultCount;
        data["SkipCount"] = this.skipCount;
        return data;
    }
}

export interface IGetUsersInput {
    filterText: string | undefined;
    sorting: string | undefined;
    maxResultCount: number;
    skipCount: number;
}

export class AssignRoleInput implements IAssignRoleInput {
    /** 用户Ids */
    userIds!: string[] | undefined;
    /** 角色Ids */
    roleIds!: string[] | undefined;

    constructor(data?: IAssignRoleInput) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["UserIds"])) {
                this.userIds = [] as any;
                for (let item of _data["UserIds"])
                    this.userIds!.push(item);
            }
            if (Array.isArray(_data["RoleIds"])) {
                this.roleIds = [] as any;
                for (let item of _data["RoleIds"])
                    this.roleIds!.push(item);
            }
        }
    }

    static fromJS(data: any): AssignRoleInput {
        data = typeof data === 'object' ? data : {};
        let result = new AssignRoleInput();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.userIds)) {
            data["UserIds"] = [];
            for (let item of this.userIds)
                data["UserIds"].push(item);
        }
        if (Array.isArray(this.roleIds)) {
            data["RoleIds"] = [];
            for (let item of this.roleIds)
                data["RoleIds"].push(item);
        }
        return data;
    }
}

export interface IAssignRoleInput {
    /** 用户Ids */
    userIds: string[] | undefined;
    /** 角色Ids */
    roleIds: string[] | undefined;
}

export class PermissionDto implements IPermissionDto {
    /** 主键 */
    id!: string | undefined;
    /** 权限Key */
    name!: string | undefined;
    /** 权限名称 */
    displayName!: string | undefined;
    /** 父节点 */
    parentId!: string | undefined;
    /** 子集 */
    children!: PermissionDto[] | undefined;

    constructor(data?: IPermissionDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.name = _data["Name"];
            this.displayName = _data["DisplayName"];
            this.parentId = _data["ParentId"];
            if (Array.isArray(_data["Children"])) {
                this.children = [] as any;
                for (let item of _data["Children"])
                    this.children!.push(PermissionDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): PermissionDto {
        data = typeof data === 'object' ? data : {};
        let result = new PermissionDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Name"] = this.name;
        data["DisplayName"] = this.displayName;
        data["ParentId"] = this.parentId;
        if (Array.isArray(this.children)) {
            data["Children"] = [];
            for (let item of this.children)
                data["Children"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IPermissionDto {
    /** 主键 */
    id: string | undefined;
    /** 权限Key */
    name: string | undefined;
    /** 权限名称 */
    displayName: string | undefined;
    /** 父节点 */
    parentId: string | undefined;
    /** 子集 */
    children: PermissionDto[] | undefined;
}

export class ListApiResponse4 implements IListApiResponse4 {
    data!: PermissionDto[] | undefined;
    code!: number;
    success!: boolean;
    message!: string | undefined;

    constructor(data?: IListApiResponse4) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["Data"])) {
                this.data = [] as any;
                for (let item of _data["Data"])
                    this.data!.push(PermissionDto.fromJS(item));
            }
            this.code = _data["Code"];
            this.success = _data["Success"];
            this.message = _data["Message"];
        }
    }

    static fromJS(data: any): ListApiResponse4 {
        data = typeof data === 'object' ? data : {};
        let result = new ListApiResponse4();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.data)) {
            data["Data"] = [];
            for (let item of this.data)
                data["Data"].push(item ? item.toJSON() : undefined as any);
        }
        data["Code"] = this.code;
        data["Success"] = this.success;
        data["Message"] = this.message;
        return data;
    }
}

export interface IListApiResponse4 {
    data: PermissionDto[] | undefined;
    code: number;
    success: boolean;
    message: string | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    throw new ApiException(message, status, response, headers, result);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}