// <auto-generated />
using System;
using FlyFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlyFramework.Migrations
{
    [DbContext(typeof(FlyFrameworkDbContext))]
    [Migration("20250811121627_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlyFramework.OrgUnitModule.OrgUnitNode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("主键");

                    b.Property<string>("ConcurrencyToken")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("并发令牌");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("创建人Id");

                    b.Property<string>("CreatorUserName")
                        .HasColumnType("text")
                        .HasComment("创建人名称");

                    b.Property<string>("DeleterUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("删除人Id");

                    b.Property<string>("DeleterUserName")
                        .HasColumnType("text")
                        .HasComment("删除人名称");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否已删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("LastModifierUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("最后修改人Id");

                    b.Property<string>("LastModifierUserName")
                        .HasColumnType("text")
                        .HasComment("最后修改人名称");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("组织机构名称");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasComment("父级Id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("状态");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasComment("租户ID");

                    b.HasKey("Id");

                    b.ToTable("OrgUnitNode");
                });

            modelBuilder.Entity("FlyFramework.OrgUnitModule.OrgUnitNodeRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("主键");

                    b.Property<string>("ConcurrencyToken")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("并发令牌");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("创建人Id");

                    b.Property<string>("CreatorUserName")
                        .HasColumnType("text")
                        .HasComment("创建人名称");

                    b.Property<string>("OrgUnitNodeId")
                        .HasColumnType("text")
                        .HasComment("节点关联的数据Id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasComment("角色Id");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasComment("租户Id");

                    b.HasKey("Id");

                    b.ToTable("OrgUnitNodeRole");
                });

            modelBuilder.Entity("FlyFramework.PermissionModule.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("主键");

                    b.Property<string>("ConcurrencyToken")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("并发令牌");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("FlyFramework.PermissionModule.RolePermission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("主键");

                    b.Property<string>("ConcurrencyToken")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("并发令牌");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("CreatorUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("创建人Id");

                    b.Property<string>("CreatorUserName")
                        .HasColumnType("text")
                        .HasComment("创建人名称");

                    b.Property<string>("DeleterUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("删除人Id");

                    b.Property<string>("DeleterUserName")
                        .HasColumnType("text")
                        .HasComment("删除人名称");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否已删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("LastModifierUserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("最后修改人Id");

                    b.Property<string>("LastModifierUserName")
                        .HasColumnType("text")
                        .HasComment("最后修改人名称");

                    b.Property<string>("PermissionId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("FlyFramework.UserModule.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .HasColumnType("text")
                        .HasComment("并发令牌");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("text")
                        .HasComment("创建人Id");

                    b.Property<string>("CreatorUserName")
                        .HasColumnType("text")
                        .HasComment("创建人名称");

                    b.Property<string>("DeleterUserId")
                        .HasColumnType("text")
                        .HasComment("删除人Id");

                    b.Property<string>("DeleterUserName")
                        .HasColumnType("text")
                        .HasComment("删除人名称");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasComment("显示名称");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasComment("是否默认角色");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否已删除");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("boolean")
                        .HasComment("是否静态角色");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("text")
                        .HasComment("最后修改人Id");

                    b.Property<string>("LastModifierUserName")
                        .HasColumnType("text")
                        .HasComment("最后修改人名称");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasComment("租户Id");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FlyFramework.UserModule.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .HasColumnType("text")
                        .HasComment("并发令牌");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("text")
                        .HasComment("创建人Id");

                    b.Property<string>("CreatorUserName")
                        .HasColumnType("text")
                        .HasComment("创建人名称");

                    b.Property<string>("DeleterUserId")
                        .HasColumnType("text")
                        .HasComment("删除人Id");

                    b.Property<string>("DeleterUserName")
                        .HasColumnType("text")
                        .HasComment("删除人名称");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasComment("用户名称");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("是否启用");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否已删除");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean")
                        .HasComment("是否超级管理员");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("text")
                        .HasComment("最后修改人Id");

                    b.Property<string>("LastModifierUserName")
                        .HasColumnType("text")
                        .HasComment("最后修改人名称");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NeedToChangeThePassword")
                        .HasColumnType("boolean")
                        .HasComment("是否需要修改密码");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OrgUnitNodeId")
                        .HasColumnType("text")
                        .HasComment("组织单元Id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasComment("租户Id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUserRole<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FlyFramework.UserModule.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>");

                    b.Property<string>("ConcurrencyToken")
                        .HasColumnType("text")
                        .HasComment("并发令牌");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("text")
                        .HasComment("创建人Id");

                    b.Property<string>("CreatorUserName")
                        .HasColumnType("text")
                        .HasComment("创建人名称");

                    b.Property<string>("DeleterUserId")
                        .HasColumnType("text")
                        .HasComment("删除人Id");

                    b.Property<string>("DeleterUserName")
                        .HasColumnType("text")
                        .HasComment("删除人名称");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否已删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("LastModifierUserId")
                        .HasColumnType("text")
                        .HasComment("最后修改人Id");

                    b.Property<string>("LastModifierUserName")
                        .HasColumnType("text")
                        .HasComment("最后修改人名称");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasComment("租户Id");

                    b.HasDiscriminator().HasValue("UserRole");
                });

            modelBuilder.Entity("FlyFramework.PermissionModule.Permission", b =>
                {
                    b.HasOne("FlyFramework.PermissionModule.Permission", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("FlyFramework.UserModule.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FlyFramework.UserModule.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FlyFramework.UserModule.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("FlyFramework.UserModule.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlyFramework.UserModule.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FlyFramework.UserModule.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlyFramework.PermissionModule.Permission", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
