<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\version.props" />
	<PropertyGroup>
		<LangVersion>$(LangVersion)</LangVersion>
		<TargetFramework>$(DotNetVersion)</TargetFramework>
		<RootNamespace>FlyFramework</RootNamespace>

	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<DocumentationFile>bin\Debug\FlyFramework.Application.xml</DocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<!--<PackageReference Include="FaceMan.DynamicAPI" Version="1.0.8" />-->
		<PackageReference Include="FluentMigrator.Abstractions" Version="6.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">

			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.4.9" />

	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\..\..\..\FaceMan.Common\src\FaceMan.DynamicAPI\FaceMan.DynamicAPI.csproj" />
	  <ProjectReference Include="..\FlyFramework.Core\FlyFramework.Core.csproj" />
	</ItemGroup>

	
</Project>
