using System;
using System.ComponentModel.DataAnnotations;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyFramework.Test
{
    
    
    /// <summary>
    /// test
    /// </summary>
    public class Test
    {
        
        /// <summary>
        /// asdf
        /// </summary>
        [MaxLength(32)]
        public string Name { get; set; }

    }
}
