using FlyFramework.Domains;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyFramework.TestModule.DomainService
{
    
    
    public class Test : GuidDomainService<Test>, ITestManager
    {
        
        public Test(IServiceProvider serviceProvider) : 
                base(serviceProvider)
        {
        }
        
        public virtual Task<Test> FindByNameAsync(@string name)
        {
            return QueryAsNoTracking.FirstOrDefaultAsync(t => t.Name == name);
        }
        
        public override IQueryable<Test> GetIncludeQuery()
        {
            throw new NotImplementedException();
        }
        
        public override Task ValidateOnCreateOrUpdate(Test entity)
        {
            return Task.CompletedTask;
        }
        
        public override Task ValidateOnDelete(Test entity)
        {
            return Task.CompletedTask;
        }
    }
}
